[package]
name = "systemfd"
version = "0.2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "A convenient helper for passing sockets into another process.  Best to be combined with listenfd and cargo-watch."
keywords = ["socket", "listenfd", "systemd", "socketactivation", "cargo-watch"]
homepage = "https://github.com/mitsuhiko/systemfd"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.31.2"
failure = "0.1.1"
regex = "1.0.0"
lazy_static = "1.0.0"
nix = "0.10.0"
libc = "0.2.40"
console = "0.6.1"
