[package]
name = "systemfd"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
clap = "2.31.2"
failure = "0.1.1"
regex = "1.0.0"
lazy_static = "1.0.0"
nix = "0.10.0"
libc = "0.2.40"
console = "0.6.1"
